### ISSUE TITLE
A little more detailed usecase documentation?

### ISSUE THREAD

**Issue by clscott** [Corion/Mail-URLFor#2]
This is a very intriguing module. What scenarios or use cases does this enable?

For example if I send a customer an "onboarding" email from my applications can I then tell them in the account page - Revisit the on boarding email by clicking here - and provide a link?

What information to I have to control/store in order to be able to create that link?

**Comment by Corion** [comment]
You need to have the content of the `Message-Id` header of the mail that was sent to the client.

If you have that message id, you can generate (different) links to open the mail in `Mail.app` (OSX) , Gmail or Thunderbird. The idea of revisiting an onboarding mail is a great idea!

The original intention is to provide tighter coupling between a local web application and the local mail clients. I read the `Message-Id` header from an IMAP folder and display the mails in the web application. Then I want to navigate back to the mail in the mail client with a click in the web application.

**Comment by Corion** [comment]
I have now added an online demo (and even a link to it in the documentation). The demo is at https://corion.net/mail-urlfor.psgi . You can paste any valid message id into it and then click on the appropriate link to see the mail.
